project3/cart/urls.py
from django.urls import path
from .views import cart_home,cart_update,checkout_home,checkout_done_view

app_name='cart'
urlpatterns=[
    path('',cart_home,name='home'),
    path('update/',cart_update,name='update'),
    path('checkout/',checkout_home,name='checkout'),
    path('checkout/success/',checkout_done_view,name='success'),
]

project3/project3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view,checkout_address_reuse_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page, name='register'),
    path('register/guest', guest_register_view, name='guest_register'),
    path('checkout/address/create/',checkout_address_create_view,name='checkout_address_create'),
    path('checkout/address/reuse/',checkout_address_reuse_view,name='checkout_address_reuse'),
    path('',include('products.urls', namespace='products')),
    path('cart/',include('cart.urls' ,namespace='cart')),
]

project3/cart/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, m2m_changed

User=settings.AUTH_USER_MODEL

# Create your models here.

class CartManager(models.Manager):


    def get_or_create(self,request):
        cart_id=request.session.get('cart_id', None)
        if cart_id is None:
            cart_obj=self.new(user=request.user)
            new_obj=True
            request.session['cart_id']=cart_obj.id
            cart_id=request.session.get('cart_id')
        else:
            qs=self.get_queryset().filter(id=cart_id)
            if qs.count()==1:
                new_obj=False
                cart_obj=qs.first()
                if request.user.is_authenticated and cart_obj.user is None:
                    cart_obj.user=request.user
                    cart_obj.save()
        return cart_obj, new_obj


    def new(self,user=None):
        user_obj=None
        if user is not None:
            if user.is_authenticated:
                user_obj=user
        return self.model.objects.create(user=user_obj)



class Cart(models.Model):
    user=models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE)
    products=models.ManyToManyField(Product, blank=True)
    total=models.DecimalField(max_digits=10,decimal_places=2,default=0.00)
    timestamp=models.DateTimeField(auto_now_add=True)
    objects=CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
    if action=='post_add' or action=='post_clear' or action=='post_remove':
        products=instance.products.all()
        total=0
        for item in products:
            total+=item.price
        instance.total=total
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through)

project3/cart/views.py
from django.shortcuts import render,redirect
from .models import Cart
from products.models import Product
from orders.models import Order
from billing.models import BillingProfile
from accounts.forms import LoginForm,GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address
# Create your views here.
def cart_home(request):
    cart_obj, new_obj=Cart.objects.get_or_create(request)
    return render(request,'cart/home.html',{'cart':cart_obj})

def cart_update(request):
    product_id=request.POST.get('product_id')
    if product_id is not None:
        cart_obj, new_obj=Cart.objects.get_or_create(request)
        product_obj=Product.objects.get(id=product_id)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
    return redirect('cart:home')



def checkout_home(request):
    cart_obj, created=Cart.objects.get_or_create(request)
    order_obj=None
    if created or cart_obj.products.count()==0:
        return redirect('cart:home')

    guest_form=GuestForm()
    login_form=LoginForm()
    address_form=AddressForm()
    billing_address_form=AddressForm()
    billing_address_id=request.session.get('billing_address_id',None)
    shipping_address_id=request.session.get('shipping_address_id',None)
    billing_profile,billing_profile_created=BillingProfile.objects.new_or_get(request)
    address_qs=None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs=Address.objects.filter(billing_profile=billing_profile)
        order_obj,created=Order.objects.new_or_get(billing_profile,cart_obj)
        if shipping_address_id:
            order_obj.shipping_address=Address.objects.get(id=shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()


    if request.method=='POST':
        is_done=order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            del request.session['cart_id']
            return redirect('cart:success')




    context={
    'object':order_obj,
    'billing_profile':billing_profile,
    'login_form':login_form,
    'guest_form':guest_form,
    'address_form':address_form,
    'billing_address_form':billing_address_form,
    'address_qs':address_qs
    }

    return render(request,'cart/checkout.html',context)



def checkout_done_view(request):
    return render(request,'cart/checkout_done.html')

project3/cart/templates/cart/checkout.html
{% extends "products/base.html" %}


{% block content %}
{% if not billing_profile %}
    <div class='row text-center'>
    <div class='col-12 col-md-6'>
        <p class='lead'>Login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class='col-12 col-md-6'>
        Continue as Guest

        {% url "guest_register" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
    </div>

    </div>

{% else %}

        {% if not object.shipping_address %}

         <div class='row'>
            <div class='col-12'>
                <p class='lead'>Shipping Address</p>
                <hr/>
            </div>
            <div class='col-6'>




                    {% url "checkout_address_create" as checkout_address_create %}
                    {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}'



             </div>
         <div class='col-6'>
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
            </div>
        </div>


        {% elif not object.billing_address %}
        <div class='row'>
            <div class='col-12'>
                 <p class='lead'>Billing Address</p>
                <hr/>
            </div>
            <div class='col-6'>

            {% url "checkout_address_create" as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
            </div>
              <div class='col-6'>
                {% url 'checkout_address_reuse' as checkout_address_reuse %}
             {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='billing' action_url=checkout_address_reuse %}
         </div>


        </div>
        {% else %}

            <h1>Finalize Checkout</h1>
            <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
            <p>Billing Address: {{ object.shipping_address.get_address }}</p>
            <p>Cart Total: {{ object.cart.total }}</p>
            <p>Shipping Total: {{ object.shipping_total }}</p>
            <p>Order Total: {{ object.total }}</p>
            <form class='form' method='POST' action="">{% csrf_token %}
                <button type='submit' class='btn btn-success'>Checkout</button>
            </form>
        {% endif %}
{% endif %}



{% endblock %}

project3/cart/templates/cart/checkout_done.html
{% extends "products/base.html" %}


{% block content %}
<div class='col-6 mx-auto py-5 text-center'>
  <h1 class='display-1'>Thank you for your order!!!</h1>
</div>

{% endblock %}

project3/cart/templates/cart/home.html
{% extends 'products/base.html'%}
{% block content %}
  <h1>cart</h1>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    {% for product in cart.products.all %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{product.title}}</td>
      <td>{{product.price}}</td>
    </tr>

    {% endfor %}
    <tr>
      <td colspan="2"></td>
      <td><b>Total: </b>{{cart.total}}</td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><a href="{% url 'cart:checkout'%}">Checkout</a></td>
    </tr>
  </tbody>
</table>
{% endblock %}